version: '3.4'

services:
  jotateste:
    image: jotateste
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:some_secure_password@db:5432/dev
      - FOO=BAR
    env_file:
      - ./.env
    volumes:
      - ./media:/app/media/:rw

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=some_secure_password
      - POSTGRES_DB=dev
    ports:
      - 5432:5432

volumes:
  postgres_data: