version: '3.4'

services:
  jotateste:
    image: jotateste
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:some_secure_password@db:5432/dev
      - FOO=BAR
    env_file:
      - ./.env
    volumes:
      - ./media:/app/media/:rw

  celery:
    image: jotateste
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis
    command: sh -c /app/entrypoint_celery.sh

  celery-beat:
    image: jotateste
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis
    command: sh -c /app/entrypoint_celery-beat.sh

  db:
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=some_secure_password
      - POSTGRES_DB=dev
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data: