# Generated by Django 5.1.6 on 2025-02-20 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the news', max_length=1024, verbose_name='title')),
                ('subtitle', models.CharField(help_text='The text the goes right bellow the title', max_length=1024, verbose_name='subtitle')),
                ('image', models.ImageField(help_text='A image that is intimatelly connected to the news', upload_to='', verbose_name='image')),
                ('content', models.TextField(help_text='The body of the news', verbose_name='content')),
                ('publising_date', models.DateTimeField(help_text='When this news should be published', verbose_name='publishing_date')),
                ('status', models.CharField(choices=[('D', 'draft'), ('P', 'published')], default='D', help_text='Is this news pubblished or not?', max_length=1, verbose_name='status')),
                ('is_pro_only', models.BooleanField(default=False, help_text='Is this news only for PRO readers?', verbose_name='is_pro_only')),
                ('author', models.ForeignKey(help_text='The editor of this news', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(help_text='What vertical this news bellogs to', on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='category')),
            ],
        ),
    ]
