# Generated by Django 5.1.6 on 2025-02-13 00:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='pubblising_date',
        ),
        migrations.AddField(
            model_name='news',
            name='publising_date',
            field=models.DateField(default=datetime.date(2025, 2, 13), verbose_name='publishing_date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_pro_only',
            field=models.BooleanField(default=False, verbose_name='is_pro_only'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('R', 'Rascunho'), ('P', 'Publicado')], default='R', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.CharField(max_length=1024, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='title'),
        ),
    ]
