# Generated by Django 5.1.6 on 2025-02-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_pubblising_date_news_publising_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publising_date',
            field=models.DateTimeField(verbose_name='publishing_date'),
        ),
    ]
