# Generated by Django 5.1.6 on 2025-02-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('I', 'JOTA_Info'), ('P', 'Jota Pro')], max_length=1),
        ),
    ]
