name: test_Django
on: [pull_request, push] # activates the workflow when there is a push or pull request in the repo
jobs:
  test_project:
    runs-on: ubuntu-latest # operating system your code will run on
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.2"
      - name: Install dependecies
        run: pip install flake8
      - name: Test with pytest
        run: |
          docker compose up -d
          docker compose exec jotateste sh -c "chmod a+x /app/media"
          docker compose exec jotateste pytest --junitxml=junit/test-results.xml . # run pytest test
      - name: Run flake8
        run: flake8 . # run flake8 test
